<?php

/**
 * @file
 * Implements hook_mail to end mail.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_mail().
 */
function sign_in_out_mail($key, &$message, $params) {

  switch ($key) {
    case 'custom_email_key':
      $message['subject'] = t('Form Submission Notification');
      $message['body'][] = t('Message: @message', ['@message' => $params['message']]);
      break;
  }

}

/**
 * Implements hook_form_alter().
 */
function sign_in_out_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#title'] = t('Signup');
    $form['name']['#title'] = t('Full Name');
    $form['name']['#description'] = t('Enter your full name.');

    $form['email'] = [
      '#type' => 'email',
      '#title' => 'Email',
    ];

    $form['checkbox '] = [
      '#type' => 'checkbox',
      '#title' => 'Enable OTP Verification',
    ];
  }

  if ($form_id == 'user_register_form') {

    $form['mobile'] = [
      '#type' => 'tel',
      '#title' => 'Mobile No',
    ];

    $form['stream'] = [
      '#type' => 'textfield',
      '#title' => 'Stream',
    ];

    $form['joining_year'] = [
      '#type' => 'date',
      '#title' => 'Joining year',
    ];

    $form['passing_year'] = [
      '#type' => 'date',
      '#title' => 'Passing year',
    ];

  }
}
